// whitelist.ts
export const whitelist = [
    "apple",
    "banana",
    "blueberry",
    "strawberry",
    "grape",
    "orange",
    "pear",
    "peach",
    "pineapple",
    "mango",
    "kiwi",
    "lemon",
    "lime",
    "cherry",
    "raspberry",
    "blackberry",
    "coconut",
    "watermelon",
    "cantaloupe",
    "honeydew",
    "plum",
    "apricot",
    "pomegranate",
    "fig",
    "papaya",
    "avocado",
    "lettuce",
    "spinach",
    "kale",
    "arugula",
    "romaine",
    "cabbage",
    "broccoli",
    "cauliflower",
    "brussels sprouts",
    "carrot",
    "celery",
    "cucumber",
    "bell pepper",
    "jalapeno",
    "onion",
    "garlic",
    "ginger",
    "beet",
    "radish",
    "turnip",
    "sweet potato",
    "potato",
    "zucchini",
    "squash",
    "eggplant",
    "corn",
    "peas",
    "green bean",
    "mushroom",
    "asparagus",
    "artichoke",
    "okra",
    "pumpkin",
    "chili pepper",
    "basil",
    "parsley",
    "cilantro",
    "thyme",
    "rosemary",
    "sage",
    "oregano",
    "mint",
    "dill",
    "chive",
    "beef",
    "steak",
    "pork",
    "ham",
    "bacon",
    "chicken",
    "turkey",
    "duck",
    "lamb",
    "veal",
    "sausage",
    "salami",
    "pepperoni",
    "ground beef",
    "ground turkey",
    "tofu",
    "tempeh",
    "shrimp",
    "lobster",
    "crab",
    "clam",
    "oyster",
    "salmon",
    "tuna",
    "cod",
    "tilapia",
    "sardine",
    "mackerel",
    "trout",
    "snapper",
    "cheddar cheese",
    "mozzarella",
    "parmesan",
    "brie",
    "goat cheese",
    "gouda",
    "swiss cheese",
    "provolone",
    "blue cheese",
    "ricotta",
    "cottage cheese",
    "yogurt",
    "milk",
    "butter",
    "cream",
    "egg"
  ];
  